### ISSUE TITLE
Wrong link in activation mail

### ISSUE THREAD

**Issue by emmerink** [GeneaLabs/laravel-registrar#1]
In your activation mail you link to:

`$url = url("/register/activate/{$notifiable->activation_token}");`

But in your routes you define:

`Route::get('/registration/activate/{activationToken}', Activation::class . '@show');`

I think the url in the mail should also read **registration** instead of **register**.

**Comment by mikebronner** [comment]
Haha, thanks for reporting this! Wow, you're quick, I haven't even officially included it in my own project yet. (Was going to start that next week.) Woot. You get a gold star, sir.

Will address this early next week.

**Comment by mikebronner** [comment]
Fixed the link and added some instructions on customizing the notifications. Please try with version 0.1.2 and let me know how it goes. :)
